#!/usr/bin/env bash

info='\e[1;36m'
warn='\e[1;33m'
error='\e[31m'

rootfs="minirootfs"
sourcefile=".sourcefile"
netsourcefile=".netsourcefile"
mountpoint="/var/lib/jkrun"
cuid=$((1000 + $RANDOM % 9000))
conoverlayfs="${mountpoint}/${cuid}"

function jkpremsg() { printf "\e[0;36m|jkrun-> ${info}"; }

function jkmsg() {
    jkpremsg; for i in {1..3}; do printf ' '; done
}

function networksetupcheck() {
    if [[ -v ${hostvenum} || -v ${convenum} ]]; then 
        jkpremsg; printf "${error}Error setting up network virtual ethernet\n" 
        jkpremsg; printf "${error}Exiting...\n"
        exit 1
    fi
}

function setnetworkvars() {
    if [[ $(ip a | grep -E "^[0-9]{1,3}:\sve") ]]; then
        for i in $(seq 2 2 100); do
            if [[ ! $(ip a | grep -E "^[0-9]{1,3}:\sve${i}") ]]; then 
                hostvenum=${i}
                break
            fi
        done
    else
        hostvenum=2
    fi
    newhostve="ve${hostvenum}"
    convenum=$((hostvenum-1))
    newconve="ve${convenum}"
    hostveip="192.168.${convenum}.200"
    conveip="192.168.${convenum}.100"

    networksetupcheck

    jkpremsg; echo "Host IP: ${hostveip}"
    jkpremsg; echo "Container IP: ${conveip}"
}

function setupnetwork() {
    # run in background
    perentpid=$(ps ajf | grep -E "unshare.*/${cuid}/" | grep -v "grep" | grep -Po "^\s+[0-9]{1,6}\s+\K[0-9]{1,6}")
    conpid=$(pgrep -P "${perentpid}")
    networksetupcheck
    sleep 1 
    ip link add "${newconve}" netns ${conpid} type veth peer name "${newhostve}" netns 1
    ip link set "${newhostve}" up
    ip addr add ${hostveip}/24 dev "${newhostve}"
}

######################
### HOST
# ip link add ve1 netns 28966 type veth peer name ve2 netns 1
# ip link set ve2 up
# ip addr add 192.168.1.200/24 dev ve2
### CONT
# ip link set ve1 up
# ip addr add 192.168.1.100/24 dev ve1
# ping 192.168.1.200
######################

while getopts 'l' OPTION; do
    case "$OPTION" in
    l)
        jkmsg; echo "Containers"
        containers=$(ls -l ${mountpoint} | grep -Po "[0-9]{4,5}$")
        for container in ${containers}; do jkmsg; echo "${container}"; done
        exit 0
        ;;
    ?)
        jkpremsg; printf "${warn}usage: jkrun [-l]"
        exit 0
        ;;
    esac
done

if [ $# -eq 0 ]; then 
    jkpremsg; printf "${warn}Whoops I need to know where the rootfs is, try something like...\n";
    jkpremsg; printf "${warn}sudo jkrun ./alpine-minirootfs-3.15.0-x86_64.tar.gz\n";
    exit 0
else
    pathtoimgtar="$1"
fi

jkpremsg; echo "${cuid}"
setnetworkvars

if [[ ! -d "${mountpoint}" ]]; then mkdir "${mountpoint}"; fi
if [[ ! -d "${conoverlayfs}" ]]; then 
    mkdir "${conoverlayfs}"
    mkdir "${conoverlayfs}/base" \
        "${conoverlayfs}/diff" \
        "${conoverlayfs}/overlay" \
        "${conoverlayfs}/work" 
else 
    jkpremsg; printf "${warn}Whoops that cuid already exists, try again.\n"
    exit 0
fi

basedir="${conoverlayfs}/base"
overlaydir="${conoverlayfs}/overlay"

tar -xf "${pathtoimgtar}" --directory "${basedir}"
mount -t overlay -o lowerdir="${basedir}",upperdir="${conoverlayfs}/diff",workdir="${conoverlayfs}/work" jkoverlay "${overlaydir}"

trap "jkpremsg; echo 'Thanks, come again!'" EXIT

# check if source file already exists
if [[ -f "${overlaydir}/${sourcefile}" ]]; then
    echo "" > "${overlaydir}/${sourcefile}"
fi

if [[ -f "${overlaydir}/${netsourcefile}" ]]; then
    echo "" > "${overlaydir}/${netsourcefile}"
fi

# commands to execute inside containerized process
cmds=(\
    "mount -t proc proc /proc" \
    "mount -t sysfs sysfs /sys" \
    "mount -t tmpfs cgroup /sys/fs/cgroup" \
    "mkdir /sys/fs/cgroup/memory" \
    "mkdir /sys/fs/cgroup/blkio" \
    "mkdir /sys/fs/cgroup/pids" \
    "mkdir /sys/fs/cgroup/rdma" \
    "mkdir /sys/fs/cgroup/freezer" \
    "mkdir /sys/fs/cgroup/devices" \
    "mkdir /sys/fs/cgroup/cpuset" \
    "mkdir /sys/fs/cgroup/cpu,cpuacct" \
    "mkdir /sys/fs/cgroup/hugetlb" \
    "mkdir /sys/fs/cgroup/misc" \
    "mkdir /sys/fs/cgroup/net_cls,net_prio" \
    "mkdir /sys/fs/cgroup/perf_event" \
    "mkdir /sys/fs/cgroup/systemd" \
    "cd /sys/fs/cgroup" \
    "ln -s cpu,cpuacct cpu && ln -s cpu,cpuacct cpuacct" \
    "ln -s net_cls,net_prio net_cls && ln -s net_cls,net_prio net_prio" \
    "cd /" \
    "mount -t cgroup -o memory,nosuid,nodev,noexec cgroup /sys/fs/cgroup/memory/" \
    "mount -t cgroup -o blkio,nosuid,nodev,noexec cgroup /sys/fs/cgroup/blkio/" \
    "mount -t cgroup -o pids,nosuid,nodev,noexec cgroup /sys/fs/cgroup/pids/" \
    "mount -t cgroup -o rdma,nosuid,nodev,noexec cgroup /sys/fs/cgroup/rdma/" \
    "mount -t cgroup -o freezer,nosuid,nodev,noexec cgroup /sys/fs/cgroup/freezer/" \
    "mount -t cgroup -o devices,nosuid,nodev,noexec cgroup /sys/fs/cgroup/devices/" \
    "mount -t cgroup -o cpuset,nosuid,nodev,noexec cgroup /sys/fs/cgroup/cpuset/" \
    "mount -t cgroup -o cpu,cpuacct,nosuid,nodev,noexec cgroup /sys/fs/cgroup/cpu,cpuacct/" \
    "mount -t cgroup -o hugetlb,nosuid,nodev,noexec cgroup /sys/fs/cgroup/hugetlb/" \
    "mount -t cgroup -o misc,nosuid,nodev,noexec cgroup /sys/fs/cgroup/misc/" \
    "mount -t cgroup -o net_cls,net_prio,nosuid,nodev,noexec cgroup /sys/fs/cgroup/net_cls,net_prio/" \
    "mount -t cgroup -o perf_event,nosuid,nodev,noexec cgroup /sys/fs/cgroup/perf_event/" \
    "mount -t cgroup -o name=systemd,nosuid,nodev,noexec,xattr cgroup /sys/fs/cgroup/systemd/" \
    "echo 1 > /sys/fs/cgroup/cpuset/cgroup.clone_children" \
    "if [[ ! -d /sys/fs/cgroup/memory/jkrun ]]; then mkdir /sys/fs/cgroup/memory/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/blkio/jkrun ]]; then mkdir /sys/fs/cgroup/blkio/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/pids/jkrun ]]; then mkdir /sys/fs/cgroup/pids/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/rdma/jkrun ]]; then mkdir /sys/fs/cgroup/rdma/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/freezer/jkrun ]]; then mkdir /sys/fs/cgroup/freezer/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/devices/jkrun ]]; then mkdir /sys/fs/cgroup/devices/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/cpuset/jkrun ]]; then mkdir /sys/fs/cgroup/cpuset/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/cpu,cpuacct/jkrun ]]; then mkdir /sys/fs/cgroup/cpu,cpuacct/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/hugetlb/jkrun ]]; then mkdir /sys/fs/cgroup/hugetlb/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/misc/jkrun ]]; then mkdir /sys/fs/cgroup/misc/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/net_cls,net_prio/jkrun ]]; then mkdir /sys/fs/cgroup/net_cls,net_prio/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/perf_event/jkrun ]]; then mkdir /sys/fs/cgroup/perf_event/jkrun; fi" \
    "if [[ ! -d /sys/fs/cgroup/systemd/jkrun ]]; then mkdir /sys/fs/cgroup/systemd/jkrun; fi" \
    "cd /sys/fs/cgroup" \
    "echo 1 | tee memory/jkrun/cgroup.procs blkio/jkrun/cgroup.procs cpu,cpuacct/jkrun/cgroup.procs devices/jkrun/cgroup.procs freezer/jkrun/cgroup.procs hugetlb/jkrun/cgroup.procs misc/jkrun/cgroup.procs net_cls,net_prio/jkrun/cgroup.procs perf_event/jkrun/cgroup.procs pids/jkrun/cgroup.procs rdma/jkrun/cgroup.procs > systemd/jkrun/cgroup.procs" \
    "cd /" \
    "hostname jkrun" \
)

netcmds=(\
    "sleep 2"
    "ip link set ${newconve} up" \
    "ip addr add ${conveip}/24 dev ${newconve} &>/dev/null" \
)

for cmd in "${cmds[@]}"; do
    echo "$cmd" >> "${overlaydir}/${sourcefile}"
done

for netcmd in "${netcmds[@]}"; do
    echo "$netcmd" >> "${overlaydir}/${netsourcefile}"
done

setupnetwork &

unshare \
    --uts \
    --pid --fork \
    --ipc \
    --mount \
    --net \
    --cgroup \
    chroot "${overlaydir}" /bin/sh -c '. '"${sourcefile}"'; . '"${netsourcefile}"';printf "\e[0m"; exec /bin/sh'
